### ISSUE TITLE
awscrt module throwing 'undefined symbol: EVP_aead_aes_128_gcm_tls13' error in ARM yocto

### ISSUE THREAD

**Issue by kiran-g** [awslabs/aws-crt-python#396] opened 2022-09-22 15:00 UTC
I have a custom ARM gateway on which I am trying to run a greengrass v2 component using awsiotsdk.  But when I import the awsiotsdk I am getting this error:

`ImportError: /usr/lib/python3.7/site-packages/_awscrt.cpython-37m-arm-linux-gnueabi.so: undefined symbol: EVP_aead_aes_128_gcm_tls13`

When I ran the same component in an x86 environment with the same awsiotsdk version, I did not get the error.

This is the difference I noticed:

ARM GATEWAY

```
bash-5.0# strings   /usr/lib/python3.7/site-packages/_awscrt.cpython-37m-arm-linux-gnueabi.so    | grep -i EVP_aead_aes_128_gcm_tls13
    EVP_aead_aes_128_gcm_tls13
    EVP_aead_aes_128_gcm_tls13
    EVP_aead_aes_128_gcm_tls13
    bash-5.0# 
```

X86 LAPTOP

  ```
  bash-4.2# strings   /usr/local/lib64/python3.7/site-packages/_awscrt.cpython-37m-x86_64-linux-gnu.so    | grep -i EVP_aead_aes_128_gcm_tls13
    EVP_aead_aes_128_gcm_tls13
    EVP_aead_aes_128_gcm_tls13_storage
    EVP_aead_aes_128_gcm_tls13_once_bss_get
    EVP_aead_aes_128_gcm_tls13_storage_bss_get
    EVP_aead_aes_128_gcm_tls13_do_init
    EVP_aead_aes_128_gcm_tls13_init
    EVP_aead_aes_128_gcm_tls13_once
    EVP_aead_aes_128_gcm_tls13_init
    EVP_aead_aes_128_gcm_tls13_storage
    EVP_aead_aes_128_gcm_tls13_once
    EVP_aead_aes_128_gcm_tls13
    bash-4.2# 
```

Btw the awscrt module in the gateway was compiled during the "pip install" step. So I thought maybe it has to do with checking of openssl features during build? Maybe the gateway does not not support TLS1.3. But it looks like the gateway does support TLS1.3 .

Openssl version : 1.1.1g

How to resolve this?

**Comment by oschwartz10612** [comment] 2022-11-10 01:47
Did you ever figure this out @kiran-g? I am having the same issue!

**Comment by kiran-g** [comment] 2022-11-10 05:38
I faced this issue when I installed aws-crt-python package via pip. This
issue got resolved when the package was installed via yocto recipe instead.
Not sure about root cause.

**Comment by oschwartz10612** [comment] 2022-11-10 05:43
Odd. Maybe I will try building it from the repository directly; I'm on Ubuntu.

Thanks so much for the reply!

**Comment by harrychoojr** [comment] 2022-11-16 18:07
Hi @oschwartz10612 ,
I am having the same issue, did you manage to solve the problem?

**Comment by oschwartz10612** [comment] 2022-11-16 18:27
No I was not able to solve the problem. I had to downgrade to Ubuntu 20.04 to get it to work.

**Comment by harrychoojr** [comment] 2022-11-16 18:40
I see. I am trying to run this on a Kali Linux ARM for Raspberry Pi Zero 2 W. Seems like I have to look for another way. 
Thanks for replying!

**Comment by arthur-proglove** [comment] 2023-01-24 21:28
I'm locally compiling `awscrt` for my Raspberry Pi 0 using `qemu-arm-static` and I get a similar issue. 
The result .so file has `EVP_aead_aes_128_gcm_tls13` undefined

```
nm _awscrt.cpython-311-arm-linux-gnueabihf.so  | grep EVP_aead_aes_128_gcm_tls13
         U EVP_aead_aes_128_gcm_tls13
```

I tried to understand why this was happening and I see the in the linker flags that the library path is set to `/usr/lib/arm-linux-gnueabihf` which contains `libcrypt.a`.  Even though the Python package is clearly setting `-Wl,--exclude-libs,libcrypto.a` it does not seem to work.
If I manually link the .so and remove `-L/usr/lib/arm-linux-gnueabihf` then the symbols are defined since it cannot find the system `libcrypt.a`.

```nm _awscrt.cpython-311-arm-linux-gnueabihf.so | grep EVP_aead_aes_128_gcm_tls13
001b9f64 t EVP_aead_aes_128_gcm_tls13
0019f3e0 t EVP_aead_aes_128_gcm_tls13_init
00300c68 b EVP_aead_aes_128_gcm_tls13_once
003007f8 b EVP_aead_aes_128_gcm_tls13_storage
```

Is there a way to solve this? On [piwheels](https://www.piwheels.org/logs/0000/0919/4077.txt) I see that their linker is only using `-L/usr/lib` and their .so libraries have the symbols defined.

**Comment by kepstin** [comment] 2023-03-09 05:22
Right, so I took a look into this and I think the problem is with the ordering of `-L` argument in the compile command, resulting in system openssl's libcrypto being linked instead of the libcrypto from aws-lc.

The link command that I get right now is:
> `x86_64-pc-linux-gnu-cc -shared -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed build/temp.linux-x86_64-cpython-310/source/auth_credentials.o build/temp.linux-x86_64-cpython-310/source/auth_signer.o build/temp.linux-x86_64-cpython-310/source/auth_signing_config.o build/temp.linux-x86_64-cpython-310/source/common.o build/temp.linux-x86_64-cpython-310/source/crc.o build/temp.linux-x86_64-cpython-310/source/crypto.o build/temp.linux-x86_64-cpython-310/source/event_stream_headers.o build/temp.linux-x86_64-cpython-310/source/event_stream_rpc_client_connection.o build/temp.linux-x86_64-cpython-310/source/event_stream_rpc_client_continuation.o build/temp.linux-x86_64-cpython-310/source/http_connection.o build/temp.linux-x86_64-cpython-310/source/http_headers.o build/temp.linux-x86_64-cpython-310/source/http_message.o build/temp.linux-x86_64-cpython-310/source/http_proxy.o build/temp.linux-x86_64-cpython-310/source/http_stream.o build/temp.linux-x86_64-cpython-310/source/io.o build/temp.linux-x86_64-cpython-310/source/module.o build/temp.linux-x86_64-cpython-310/source/mqtt5_client.o build/temp.linux-x86_64-cpython-310/source/mqtt_client.o build/temp.linux-x86_64-cpython-310/source/mqtt_client_connection.o build/temp.linux-x86_64-cpython-310/source/pkcs11_lib.o build/temp.linux-x86_64-cpython-310/source/s3_client.o build/temp.linux-x86_64-cpython-310/source/s3_meta_request.o build/temp.linux-x86_64-cpython-310/source/websocket.o -L/usr/x86_64-pc-linux-gnu/lib -Lbuild/temp.linux-x86_64-cpython-310/deps/install/lib64 -l:libaws-c-s3.a -l:libaws-c-mqtt.a -l:libaws-c-auth.a -l:libaws-c-http.a -l:libaws-c-event-stream.a -l:libaws-c-compression.a -l:libaws-checksums.a -l:libaws-c-io.a -l:libaws-c-cal.a -l:libcrypto.a -l:libaws-c-sdkutils.a -l:libaws-c-common.a -l:libs2n.a -l:libcrypto.a -lrt -o build/lib.linux-x86_64-cpython-310/_awscrt.cpython-310-x86_64-linux-gnu.so -Wl,--exclude-libs,libcrypto.a -pthread`

In this command, the library search dirs are `-L/usr/x86_64-pc-linux-gnu/lib -Lbuild/temp.linux-x86_64-cpython-310/deps/install/lib64`. The first option is my system include dir where openssl's libcrypto.a is present. This was added by setuptools (distutils) in this code:
https://github.com/pypa/setuptools/blob/bfd92b008cbda2c1252eddd2f3e54b91f61969fb/setuptools/_distutils/command/build_ext.py#L237-L240
The problem is that because of the way the setup.py is appending to the library dirs here:
https://github.com/awslabs/aws-crt-python/blob/f6bc9fbdd55b335de0b87adae28a33864b0ce4e6/setup.py#L269
The directory with the correct libcrypto.a is added *after* the system directory with openssl's libcrypto.a, so the linker uses the wrong library.

I wonder if the code that determines the library (and include) directories in the `run()` can be moved to the `awscrt_ext()` method and passed to the `setuptools.Extension` constructor, so they'll be in the correct relative order.

I ended up doing a really simple workaround: I changed the `self.library_dirs.append(…` to `self.library_dirs.insert(0, …` to make sure the directories are in the correct order.

**Comment by graebm** [comment] 2023-03-13 21:20
Thank you @kepstin for the exacting diagnosis

**Comment by graebm** [comment] 2023-03-13 21:52
The solution proposed by @kepstin is committed to main, tagged as v0.16.2, and will shortly be in pypi as 0.16.2

Does that fix it?

**Closed** 2023-03-16 22:20 UTC
